### ISSUE TITLE
Search with GET instead of POST

### ISSUE THREAD

**Issue by optilude** [floralvikings/jira-connector#10]
Hi,

I have a search that uses `expand="changelog"`. I'm porting some code from a Python script, where it so happens that the `search` API abstraction chooses to use a GET request. In `jira-connector`, the `search.search()` method uses  POST.

I think JIRA allows both and treats them more or less equally, but with POST, trying two different JIRA instances with very different data, I get a server-side error back. This may be a bug in the JIRA REST API, I'm not sure.

The error is: `Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token`

So, small request: can we allow the method to be specified in the options passed to `search()`?

I tried very quickly to hack the code to use `method: 'GET'`, but I don't think the parameters are actually marshalled to the query string so that returned a lot of issues! :)

Martin

**Comment by floralvikings** [comment]
So the reason I went with POST instead of GET for that particular function is that JQL queries can get pretty long pretty quickly, and I didn't want anyone to worry about hitting the URL length limit (which, at 2000 characters, is admittedly unlikely).  

JIRA should treat both exactly the same, but I've found the REST API to be occasionally inconsistent so there might be something going on there.

Would you mind supplying an example that causes this error?

**Comment by optilude** [comment]
Hi,




In my tests the trigger is to set expand="changelog". I've tried two projects on two different cloud instances.




The query was very simple. Filter by issue type, resolution and order by key.




Martin



—

**Comment by optilude** [comment]
Sorry, was on my phone. The exact query I tried was (more-or-less):

    issueType IN ("Feature") AND (resolution IS EMPTY OR resolution IN ("Done")) AND project = ABC ORDER BY KEY ASC

It works with a GET request (from the `jira` Python client), and fails with a `POST` (from the `jira-connector` JavaScript client).

Martin

**Comment by goober** [comment]
@optilude are you settings the `expand` property as an array? e.g. `expand: ['changelog']`? I got the same error message and it was caused by setting the expand property to a string value instead of an array.

**Comment by optilude** [comment]
Holy crap! That did it. :)

So, it seems the JIRA API expects a string when using GET and an array when using POST.  https://docs.atlassian.com/jira/REST/latest/#d2e3351 doesn't seem to document that at all.

Thank you!

**Comment by iamdcchetan** [comment]
I tried to get the issues using the following code 

 `const issues = await jira.search.search({jql: 'project=TEST AND expand=changelog'});`

And got the following error

`"Field 'expand' does not exist or you do not have permission to view it."`

Am I using the correct syntax? If not, can you please suggest the correct syntax?
