### ISSUE TITLE
Stub

### ISSUE THREAD

**Issue by adewergifosse** [floralvikings/jira-connector#100]
Hi,

Could you provide an option in the constructor that would return a function jira-connector, but with stubs ?
This would be very useful for unit testing function using your connector.

Thank you,

**Comment by floralvikings** [comment]
This repository is only _very_ lightly maintained; you are welcome to submit a pull request if there is behavior you'd like to add, I do occasionally check the PR list and merge code that is within the scope of this tool and doesn't include breaking changes.  

If you have found a bug please indicate the desired behavior and provide a minimal example demonstrating the incorrect behavior; I do try to fix bugs as they come up but I have very little time to devote to this repository anymore, so I can't make any guarantees.

If you have a feature you'd like to request, please indicate the desired behavior.  I will almost certainly never have the time to implement it myself but this repository does see occasional PR activity so it may be added by a generous contributor.  You are, of course, welcome to submit a pull request yourself implementing the desired behavior.

**Comment by MrRefactoring** [comment]
I think it is most logical that this be done on the testing side. That is, I suggest using a library like [Sinon.JS](https://sinonjs.org) for this, rather than adding this functionality here
