### ISSUE TITLE
Add types support for typescript

### ISSUE THREAD

**Issue by tomasbruckner** [floralvikings/jira-connector#104]
Add types support for typescript would be quite handy.

**Comment by MrRefactoring** [comment]
You can find `typescript` support in my implementation of the wrapper for jira: [jira-api-wrapper](https://github.com/MrRefactoring/jira-api-wrapper)

**Comment by floralvikings** [comment]
This repository is only _very_ lightly maintained; you are welcome to submit a pull request if there is behavior you'd like to add, I do occasionally check the PR list and merge code that is within the scope of this tool and doesn't include breaking changes.  

If you have found a bug please indicate the desired behavior and provide a minimal example demonstrating the incorrect behavior; I do try to fix bugs as they come up but I have very little time to devote to this repository anymore, so I can't make any guarantees.

If you have a feature you'd like to request, please indicate the desired behavior.  I will almost certainly never have the time to implement it myself but this repository does see occasional PR activity so it may be added by a generous contributor.  You are, of course, welcome to submit a pull request yourself implementing the desired behavior.

**Comment by MrRefactoring** [comment]
Added in version 2.13.0
