### ISSUE TITLE
Can't update an Issue

### ISSUE THREAD

**Issue by cmoulliard** [floralvikings/jira-connector#111]
I'm a bit lost about the syntax to be used to update an issue

This code fails and returns this error : `Error: Missing Issue ID or Key`

```
    cli = new JiraClient({
        host: HOST,
        basic_auth: {
            base64: $.convertToBase64(USERNAME,PASSWORD)
        }
    })
    issueUpdate = {
        "fields" : {
            "summary": "Summary 111",
            "description": "Description 111",
        }
    }
    cli.issue.editIssue({
        issue: 'SB-896'
    }, issueUpdate)
```

What is the syntax and format to be used to edit an issue ?

**Comment by floralvikings** [comment]
In this code:
```
    cli.issue.editIssue({
        issue: 'SB-896'
    }, issueUpdate)
```

You're using `issue` as your parameter; the method expects *either* `issueId` *or* `issueKey`, so it's not going to work.  Try changing that field from `issue` to `issueKey`.
