### ISSUE TITLE
Is this node module or project

### ISSUE THREAD

**Issue by sourabhsurana1008** [floralvikings/jira-connector#116]
I am trying to using this as module in existing node project i am getting error. 

> Cannot find module jira-connector

type: 'Error',
  stack: 'Error: Cannot find module 'jira-connector'    at Function.Module._resolveFilename

**Comment by MrRefactoring** [comment]
This is node module. Write in cmd/terminal in your project folder: `npm i jira-connector`

**Comment by MrRefactoring** [comment]
I think you forgot to do `npm i jira-connector`
