### ISSUE TITLE
getIssueForBoard under board.js error in fields option

### ISSUE THREAD

**Issue by uptownaravi** [floralvikings/jira-connector#118]
when using getIssueForBoards option under board.js getting error 
 fields: opts.fields.join(',') TypeError: Cannot read property 'join' of undefined

but when I remove this field from qs section in board,js file the code works and gives the result of issues in the given board Id.

is the fields option mandatory when using getIssueForBoards ?
or am I missing something here ?

**Comment by floralvikings** [comment]
Not sure what's going on here; I'll try to make some time this weekend to take a look, but I probably accidentally made/merged a breaking change without realizing it.

**Comment by MrRefactoring** [comment]
Hi, @uptownaravi!

My changes resulted in this error.
You are completely right, this is an optional parameter.

**Comment by uptownaravi** [comment]
Thank you @MrRefactoring for the fix. Hope that pull request get merged.

**Comment by MrRefactoring** [comment]
Fixed in version 2.11.0
