### ISSUE TITLE
AuthClient logout throws unexpected excepti

### ISSUE THREAD

**Issue by tobley** [floralvikings/jira-connector#133]
AuthClient logout has a paren in the wrong place of its return statement

this.jiraClient.makeRequest(options, callback), 'User logged out.';

 - should be this

return this.jiraClient.makeRequest(options, callback, 'User logged out.');

An unexpected exception is seen when sending a bad logout request (e.g. attempt to logout when not logged in).

**Comment by MrRefactoring** [comment]
Solved in 2.12.0 version
