### ISSUE TITLE
auth.currentUser isn't using the right version of the API

### ISSUE THREAD

**Issue by svachon2** [floralvikings/jira-connector#135]
In auth.js, method currentUser is using:

uri: this.jiraClient.buildURL('/session'),

this should be 

uri: this.jiraClient.buildAuthURL('/session'),

in order to use the right authentication API version

**Comment by svachon2** [comment]
workaround: To validate if a session still active, we can use myself.getMyself(false) instead of auth.currentUser()

**Comment by MrRefactoring** [comment]
I corrected this error. Given the update rate of this library, I would use my [version](https://github.com/MrRefactoring/jira-api-wrapper)

**Comment by marias-truelogic** [comment]
@MrRefactoring  I tried using your library, but I'm getting a:

`const api = new JiraApi({` is not a constructor. Ideas? (Not TS)

**Comment by MrRefactoring** [comment]
Fixed in version 2.11.0
