### ISSUE TITLE
JWT auth

### ISSUE THREAD

**Issue by mochja** [floralvikings/jira-connector#136]
Hello,

Jira also supports JWT autorization: https://developer.atlassian.com/cloud/jira/platform/authentication-for-apps/

is there plan to support this auth?

Currently I'm attaching authorization header in dirty way and I was able to perform simple GET request (getIssue method).
```js
  const jwt = require('atlassian-jwt')
  const makeRequest = Jira.prototype.makeRequest

  Jira.prototype.makeRequest = function (options, callback, successString) {
    const now = moment().utc()
    const url = new URL(options.uri)

    const tokenData = {
      'iss': 'connect-app', // app key
      'iat': now.unix(), // the time the token is generated
      'exp': now.add(3, 'minutes').unix(), // token expiry time (recommend 3 minutes after issuing)
      'qsh': jwt.createQueryStringHash({
        method: options.method,
        pathname: url.pathname
      })
    }

    const token = jwt.encode(tokenData, secret)

    if (!options.headers) {
      options.headers = {}
    }

    options.headers['Authorization'] = 'JWT ' + token

    return makeRequest.apply(this, [options, callback, successString])
  }
```

**Comment by MrRefactoring** [comment]
Good day! Thanks for the notice of new features. Tell me, could you test the changes if I submitted them for consideration?

**Comment by MrRefactoring** [comment]
Can you comment on how best to arrange this for initialization? Is it possible to put on the `JWT` along with basic_auth and `oauth`? Or does it have any other meaning and can be used with `basic_auth` and `oauth`?

**Comment by mochja** [comment]
I think for initialization it would have to be under different option. With some defaults for token itself and secret.

It could be also generalized with some before request handler, that would have access to full request data so signature could be created, then mutate the request with additional header.

**Comment by b8394edf** [comment]
Hi, any update on this?

**Comment by MrRefactoring** [comment]
Hi, I can’t find free time to solve this problem. I can look at your PR if you are ready to help.

**Comment by ItamarM** [comment]
@MrRefactoring here you go https://github.com/floralvikings/jira-connector/pull/226
