### ISSUE TITLE
autentication with protocol, apiVersion and strictSSL

### ISSUE THREAD

**Issue by simSim305** [floralvikings/jira-connector#141]
Hello,

it does not work and with the module "jira-client" there was the possibility during the authentication to enter protocol, apiVersion and strictSSL and there it worked.
Without this data it will not work for me and I need the module jira-connector for jira-grafana.

Can someone help me there?

const jira = new JiraClient({
  protocol: 'https',
  host: '',
    username: '',
    password: '',
  apiVersion: '2',
  strictSSL: false
})

**Comment by simSim305** [comment]
Hello,

it's important :(

**Comment by floralvikings** [comment]
This repository is only _very_ lightly maintained; you are welcome to submit a pull request if there is behavior you'd like to add, I do occasionally check the PR list and merge code that is within the scope of this tool and doesn't include breaking changes.  

If you have found a bug please indicate the desired behavior and provide a minimal example demonstrating the incorrect behavior; I do try to fix bugs as they come up but I have very little time to devote to this repository anymore, so I can't make any guarantees.

If you have a feature you'd like to request, please indicate the desired behavior.  I will almost certainly never have the time to implement it myself but this repository does see occasional PR activity so it may be added by a generous contributor.  You are, of course, welcome to submit a pull request yourself implementing the desired behavior.
This repository is only _very_ lightly maintained; you are welcome to submit a pull request if there is behavior you'd like to add, I do occasionally check the PR list and merge code that is within the scope of this tool and doesn't include breaking changes.  

If you have found a bug please indicate the desired behavior and provide a minimal example demonstrating the incorrect behavior; I do try to fix bugs as they come up but I have very little time to devote to this repository anymore, so I can't make any guarantees.

If you have a feature you'd like to request, please indicate the desired behavior.  I will almost certainly never have the time to implement it myself but this repository does see occasional PR activity so it may be added by a generous contributor.  You are, of course, welcome to submit a pull request yourself implementing the desired behavior.

**Comment by MrRefactoring** [comment]
Please try changes #145. Give feedback so that we can understand if it works for you.

**Comment by MrRefactoring** [comment]
Solved in 2.12.0 version
