### ISSUE TITLE
Why there is no function to get all worklogs of issue

### ISSUE THREAD

**Issue by hmagdy** [floralvikings/jira-connector#153]
I can see there is **deleteWorklog** and **addWorklog**, but no function for **getWorklogs**.

Is there any logic behind that?

**Comment by MrRefactoring** [comment]
Hey. Perhaps this function is simply not added. You can add this feature yourself or wait for me to free myself and I can add it myself. Thanks for catching

**Comment by hmagdy** [comment]
Oh sorry .. wrong flag ... found it on https://github.com/floralvikings/jira-connector/blob/390b52f597657d7d4fb228209cdba0f1485b8513/docs/jira-connector/1.10.0/api_issue.js.html#L738

my bad :(

**Comment by MrRefactoring** [comment]
It's okay, it happens)

**Comment by MrRefactoring** [comment]
HTML documentation is outdated if that. It needs to be updated or deleted ...
