### ISSUE TITLE
XSRF check failed on adding attachment

### ISSUE THREAD

**Issue by liemnt** [floralvikings/jira-connector#161]
Hi,
I had a problem with adding attachment
the server return {"statusCode":404,"body":"XSRF check failed"}
I did research and found this: https://community.atlassian.com/t5/Jira-Core-questions/REST-API-returns-XSRF-check-failed-when-adding-attachment-to-an/qaq-p/418292
Can you open options param to allow me to custom the headers for adding attachment api ?
position: api/issue.js -> line 1064
I want to add header: X-Atlassian-Token: nocheck to this api

**Comment by MrRefactoring** [comment]
Added in version `2.15.0`
