### ISSUE TITLE
config: strictSSL param

### ISSUE THREAD

**Issue by gioboa** [floralvikings/jira-connector#174]
Hi, in [this commit](https://github.com/floralvikings/jira-connector/commit/21314579fde987f529b222465ecad289e39e1f55#diff-168726dbe96b3ce427e7fedce31bb0bc) strictSSL param was added.
Now I figure out the case if I want pass strictSSL = undefined (aka not pass the param).
In http/https request if I don't pass the strictSSL param is equal to strictSSL = true?
Thanks 👍

**Comment by MrRefactoring** [comment]
Hi! Hm you're right

**Comment by MrRefactoring** [comment]
Fixed in version `2.15.6`
