### ISSUE TITLE
getAllProjects marked deprecated - does this make sense?

### ISSUE THREAD

**Issue by theogravity** [floralvikings/jira-connector#177]
We've noticed that `getAllProjects` is marked deprecated, which causes our linter to fail.

We use the data center version of Jira, which uses the v2 REST API (it's not clear when data center will get v3), while the Jira cloud version has v3 in beta.

v3 does note that `getAllProjects` will be removed, but I doubt this would happen for v2.

Given that the endpoints defined in this lib is for v2, does it make sense to mark it as deprecated?

Following up with that, is there an option to set the API to use v2 or v3?

**Comment by MrRefactoring** [comment]
Good day! Thank you for your comment. Indeed, you are right, I will make changes. Now there is no possibility to choose v2 or v3 of API.

**Comment by MrRefactoring** [comment]
Fixed in version 2.15.7. Thanks

**Comment by gioboa** [comment]
@MrRefactoring can you implement the possibility to choose the version for this API?
Choose the version for all the API can be great.
