### ISSUE TITLE
transitionIssue example needed

### ISSUE THREAD

**Issue by svapreddy** [floralvikings/jira-connector#18]
I am trying to transition issue to done state using below code  
  
    jira.status.getAllStatuses({
       issueKey: task.ticket
    }, function(err, statuses) {
       var doneStatus = (statuses.filter(function(status) {
          return status.name === 'Done';
       }))[0];
       jira.issue.transitionIssue({
         issueKey: task.ticket,
         transition: { id: doneStatus.statusCategory.id }
       }, function() {
         console.log(arguments);
      });
    });

But this does not seem to be working. Any example would be very helpful.

Thanks in Advance.

**Comment by greggilbert** [comment]
@svapreddy I just hit the same issue; PR is in for a fix.

**Comment by floralvikings** [comment]
@greggilbert Thanks!  Merged and published as 1.7.0

**Comment by svapreddy** [comment]
Thanks guys :+1:
