### ISSUE TITLE
The users/search endpoint is not supported

### ISSUE THREAD

**Issue by roman-acumen** [floralvikings/jira-connector#180]
Currently the endpoint **users**/search [API link](https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-users-search-get) is not supported. Only **user**/search is. **user**/search contains a bug limiting it to only first 1000 users. [Bug link](https://jira.atlassian.com/browse/JRASERVER-29069?focusedCommentId=1926116&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1926116)

Please add.

**Comment by MrRefactoring** [comment]
Thanks! Will be added in next release.

**Comment by roman-acumen** [comment]
@MrRefactoring 10x. When will the next release will be shipped?

**Comment by MrRefactoring** [comment]
I would like to close the issue #179 and make release

**Comment by MrRefactoring** [comment]
@roman-acumen released in version 2.16.0
