### ISSUE TITLE
Choose the version for getAllProjects

### ISSUE THREAD

**Issue by MrRefactoring** [floralvikings/jira-connector#186]
@MrRefactoring can you implement the possibility to choose the version for this API?
Choose the version for all the API can be great.

_Originally posted by @gioboa in https://github.com/floralvikings/jira-connector/issues/177#issuecomment-514194144_

**Comment by MrRefactoring** [comment]
Hi @gioboa! This feature added in `2.16.1` version 😉

**Comment by gioboa** [comment]
Thanks :+1: :smile:
