### ISSUE TITLE
Cannot update any part of the JIRA issue

### ISSUE THREAD

**Issue by elizyu** [floralvikings/jira-connector#187]
Hello, 
I've ran several methods that were supposed to update the jira issue on the website. The console log returned messages that seemed to indicate the methods are running properly. However, when I refreshed the jira issue webpage, no change occurred.  I wonder if anyone has experienced the similar problem? 

```javascript
jira.issue.editIssue({ issueKey: "ENSTI-130", issue : { key: 'ENSTI-130',  fields: { summary: 'dummy issue' }}, (error, result) => {
    if(error){
        console.log(error);
    } else {
        console.log(result);
    }
});
```
As a result, I get this:
```sh
Issue Updated
```

```javascript
jira.issue.addComment({issueKey: "ENSTI-130", comment: "Dummy Comment"}, function(error, result) {
    if(error){
        console.error(error);
    } else {
        console.log(error);
    }
}
```
This returned:

```sh
{ startAt: 0, maxResults: 1048576, total: 0, comments: []}
```

```javascript
jira.issue.deleteComment({ issueKey: "ENSTI-130", commentId: ‘162907’ }，(error, result) => {
    if(error) {
        console.error(error);
    } else {
        console.log(result);
    }
})
```
This returned:

```sh
Comment Deleted
```

**Comment by DesignyourCode** [comment]
I'm not sure if it is related. But I am experiencing an issue with adding a comment in the same way you are above, if I try to set the visibility of the comment, it does not do it. But everything indicates that it should have worked.

**Comment by MrRefactoring** [comment]
Nice catch! I hope the corrections help you. Check `2.16.1` version. Thanks for the contribution!
