### ISSUE TITLE
404: trying to get the avatars of the user /rest/api/2/user/avatars?username='username'

### ISSUE THREAD

**Issue by Farhan-Haseeb** [floralvikings/jira-connector#198]
```
jira.user
        .getAvatars({ username: "syed.farhan" })
        .then(data => {
          console.log(data, "avatar data");
        })
        .catch(err => {
          console.log(err, "err is here");
        });
```
I am using jira.user.getAvatars function to get profile image of a user but I think the api is deprecated. Couldn't find any documentation on `/rest/api/2/user/avatars?username='username'`  of jira's official REST APIs [docs](https://developer.atlassian.com/cloud/jira/platform/rest/v2/)

**Comment by MrRefactoring** [comment]
Hi, @Farhan-Haseeb! As I can see, this method has disappeared from the documentation. You may need to find another method to get user avatars.
