### ISSUE TITLE
#18 breaks transitioning fields

### ISSUE THREAD

**Issue by Mustek** [floralvikings/jira-connector#21]
The fix implemented for issue #18 breaks transitioning fields.

Before I was able to also change the Resolution of the ticket. After the change it only allows it to change the status.

````
transition: {
            transition: {id: 5},
            fields:     {resolution: {name: 'Duplicate'}},
            update:     {
                comment: [{add: {body: util.format(CLOSEREASON.Duplicate, dupe_of)}}]
            }
        }
````
This changes the status to Resolved, Resolution to Duplicate and adds a comment.

After the change:
````
{           
        transition: {id: 5},
        fields:     {resolution: {name: 'Duplicate'}},
        update:     {
            comment: [{add: {body: util.format(CLOSEREASON.Duplicate, dupe_of)}}]
        }
}
````
Fields and Update get ignored, I see no way to do them.

**Comment by floralvikings** [comment]
Yeah I think I see what happened there; I'm a little short on time this week but I'll try and get it fixed ASAP in a way that works for everyone

**Comment by Mustek** [comment]
Thanks, I've rolled back the change on my local copy for now.

**Comment by floralvikings** [comment]
I've published a fix (v1.9.0) that should take care of the problem; transitioning issues should now work as expected whether you're using the new or the old way of passing arguments.  Can you confirm that it's working as expected for you?

**Comment by Mustek** [comment]
:thumbsup: Works as expected.

**Comment by floralvikings** [comment]
Awesome :smile:
