### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by G-Rath** [floralvikings/jira-connector#213]
It'd be good if we could have a new release, as there's been a number of useful changes.

In particular for me, `getUser` supports `accountId` on `master`, but not on the latest published version :(

**Comment by MrRefactoring** [comment]
I think this is a good idea. Only I have to understand we made problems with backward compatibility or not?

**Comment by MrRefactoring** [comment]
I looked through diff and I think it might hurt users, a new major version should be released

**Comment by MrRefactoring** [comment]
Published as `3.0.0`
