### ISSUE TITLE
board.createBoard returning java errors

### ISSUE THREAD

**Issue by agedgouda** [floralvikings/jira-connector#235]
When I run the following in my node/express app:
jira.board.createBoard({
  		"name":"board 2",
     		"type":"scrum",
     		"filterId": 10077,
     		"location": {
     		    "type": "project",
     		    "projectKeyOrId": 10079
     		}
})		

I get an error message that begins:
{"statusCode":500,"body":{"message":"Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: org.apache.catalina.connector.CoyoteInputStream@46ba7b6d; 

I am able to run the cURL command with the same data, but it creates a private board. Are the two issues related? If not, what am I doing wrong?

Thanks!

**Comment by MrRefactoring** [comment]
As I see, you should pass parameters sequentially, not an object.

Check: https://github.com/floralvikings/jira-connector/blob/master/api/board.js#L89

**Comment by agedgouda** [comment]
That was it, thanks!
