### ISSUE TITLE
Any reason for the custom file store?

### ISSUE THREAD

**Issue by rjgoldsborough** [floralvikings/jira-connector#27]
This is more of a question but I was curious why you chose to use tough-cookie-filestore over a straight request jar.

I mostly ask because tough-cookie-filestore is outdated and I am having trouble getting tough-cookie working but a straight request.jar() seems to work fine.

Thanks in advance.

**Comment by floralvikings** [comment]
There's no particular requirement to use `tough-cookie-filestore` as far as I'm aware; that's simply the example that @ngotchac included when he submitted PR #6 (which included the cookie jar functionality).

**Comment by rjgoldsborough** [comment]
Ahh. Cool. Thanks.
