### ISSUE TITLE
user.getUser broken when using expand param

### ISSUE THREAD

**Issue by rjgoldsborough** [floralvikings/jira-connector#32]
This commit adds the expand param https://github.com/floralvikings/jira-connector/commit/ea53fd8fbe9431fd2106551587eff8409d96f8a5 but that causes an authentication issue when hitting jira. 

This is because the docs say to provide an expand object. This is similar to getIssue but it gets iterated and parsed into a string over there. https://github.com/floralvikings/jira-connector/blob/master/api/issue.js#L995

The user methods do not have a buildRequestOptions function so I've fixed this by just iterating over the expand fields in the getUser function. https://github.com/rjgoldsborough/jira-connector/tree/fix-user-expand.

Let me know if you'd prefer a buildRequestOptions in the user file or maybe it's time to move it to the jiraClient file like the makeRequest function.

**Comment by floralvikings** [comment]
Yeah buildRequestOptions should probably be in jiraClient; when I initially wrote most of these functions, I don't think I realized that the expand parameter could be used in so many places.  I'll merge your PR for now and look into making the buildRequestOptions function more generic; I don't have a testing JIRA project set up anymore, though, so it might take me a while to get the code all tested.

**Comment by rjgoldsborough** [comment]
Great, thanks. I have a test jira and am actively working with jira-connector so I may take a crack at adding this in more generically.
