### ISSUE TITLE
Sprint issues or RapidView issues?

### ISSUE THREAD

**Issue by William-Olson** [floralvikings/jira-connector#36]
I can connect and get good responses from the requests. Very nice library by the way.

However, I am trying to figure out if there is a way to get all issues, or all issues for a given sprint.

I did not see any Sprint or RapidView clients in the code.  Is this possible?

If not is there a way I can go about this with this library?

Thanks in advance.

**Comment by William-Olson** [comment]
I did find a way with just using the basics...

```
request({
  uri: 'https://{jira_url}/rest/agile/1.0/board/{board_id}/issue',
  method: 'GET',
  json: true,
  followAllRedirects: true,
  jar: jar
}, (er, resp) => {
  if(er) return console.error(er);
  console.log(resp.body);
});
```

This uses the newest Jira API which includes agile stuff ( [link](https://docs.atlassian.com/jira-software/REST/cloud/#agile/1.0/board-getIssuesForBoard) ), also uses paging params as well.

It would be nice to use this library though.

**Comment by floralvikings** [comment]
I don't have any plans of adding support for the new endpoints in the *immediate* future, but I will hopefully get the time to take care of it this summer.

You're welcome to add the specific ones you want yourself and submit a pull request; there's no need to cover all of them right out of the gate, and any little bit that is added now will save work later.

**Comment by William-Olson** [comment]
:+1:  Cool.  Not sure if you want to leave this issue open or not - so I will let you close it if desired.
Thanks for the response.

Once I have some free time I would definitely like to help out.
