### ISSUE TITLE
Support promises

### ISSUE THREAD

**Issue by JonahTurnquist** [floralvikings/jira-connector#37]
Great library :)

I think it would be great to migrate to request-promise: https://www.npmjs.com/package/request-promise

Who doesn't <3 promises?

**Comment by floralvikings** [comment]
That seems like a **big** change.  Not that I'm completely against doing it, but it's definitely going to be quite involved, and I'd want to preserve backwards compatibility with existing code.  

I will definitely keep this issue open and look into it further when I've got more time to properly scope it out.

**Comment by JonahTurnquist** [comment]
I would not attempt to keep backwards compatibility with the change. See the response here: http://stackoverflow.com/questions/23501146/creating-node-library-that-support-both-node-callbacks-and-promise-with-bluebird

It just gets too messy.  Promises are much better anyways. I would push it as a major version release since it would be backwards incompatible. Of course there are downsides to this.

I just might be able to write the change and initiate a pull request myself if you approve. Otherwise I won't bother or I might consider making it a new fork.

Another option is to write a wrapper library which wraps jira-connector but replaces callbacks with promises.  I've already written such a thing for jira-connector.. But there are downsides to that as well.

Some of the more savvy node developers might be more keen to use this project versus others such as https://github.com/jira-node/node-jira-client if it supported promises directly

**Comment by JonahTurnquist** [comment]
The changes would actually be not too bad:

* Replace request with request-promise library (it's just a wrapper around request)
* Remove all callback parameters (quick search/replace)

Changing the tests might take more time..

**Comment by floralvikings** [comment]
After giving this a lot of thought, I'm going to have to decline for now.  There is already a nontrivial user base with existing code utilizing callbacks, and I'm not willing to break their ability to get new updates.  This is also the only request I've received in the 18+ months that jira-connector has been around.

That being said, if I see a lot of requests coming in for this change, I will definitely reconsider, and possibly start moving in that direction.  

I *do*, however, like the idea of a wrapper API.  I'm not a huge fan of promises in general, but I realize that a significant portion of Node.js developers are, and I'd like not to potentially alienate them.  So, if you want to publish the wrapper you've already written, I'd be happy to link it at the top of the README for developers who prefer promises to callbacks.

I'll also keep this issue open so it doesn't fall off my radar, in case this change starts gaining support.

**Comment by kyptov** [comment]
I added promise support to fork. Changes very simple: no new dependencies, backward compatibility.

**Comment by jmls** [comment]
In another project, I've made a change to a callback-based system which supports both promises and callbacks with backwards capabilities - so perhaps that may be a solution...

old code:

```js
 function doSomthing(options,callback) {
  [ blah blah blah]

  callback(err,somedata)
}
```

new  function:

```js
 function doSomthing(options,callback) {
  return new Promise((resolve, reject) => {
    [ blah blah blah]

   return callback ? callback(err,somedata) : resolve(somedata)
  });
}
```
this way, old code using callbacks still work (as it's using the callback function as before) and new code using promises work (just don't pass in the callback function)

maybe this will be of some help. I do like promises. I don't like a lot of forks ;) and it seems a shame to have  a fork simply to support promises

**Comment by jmls** [comment]
update: I've looked at the fork from @kyptov , and the only change I would make is in `index.js` where he's made it a little more complicated than it needs to be

the revised `index.js` code could be as simple as :

```js
return new Promise((resolve,reject) => {

            request(options, function (err, response, body) {
                if (err || response.statusCode.toString()[0] != 2) {
                    return callback ? callback(err ? err : body, null, response) : reject(err ? err : body);
                }

                if (typeof body == 'string') {
                    try {
                        body = JSON.parse(body);
                    } catch (jsonErr) {
                        return callback ? callback(jsonErr, null, response) : reject(jsonErr);
                    }
                }

                let result = successString ? successString : body;

                return callback ? callback(null, result,response) : resolve({result, response});
            });

        })
```
where we have simply wrapped the existing request in a promise

**Comment by floralvikings** [comment]
See #55
