### ISSUE TITLE
Get the issues which are in selected status

### ISSUE THREAD

**Issue by samundrak** [floralvikings/jira-connector#38]
I didn't find the api to get the list of status which are in current status,
Like i wana get all the status which are in In Progress?

**Comment by floralvikings** [comment]
Sounds like you want to use a JQL search; that's a pretty specific thing to want a generic API wrapper to do.

Check out [this page](https://confluence.atlassian.com/jiracore/blog/2015/07/search-jira-like-a-boss-with-jql) for a quick guide on JQL and searching in Jira.  You can use the [search](https://github.com/floralvikings/jira-connector/blob/master/api/search.js) endpoint to perform a JQL query.
