### ISSUE TITLE
fs is no longer available

### ISSUE THREAD

**Issue by miguel-orange** [floralvikings/jira-connector#48]
Hello,
jira-connector depends on fs and it seems that package is no longer available.
[see npm message](https://www.npmjs.com/package/fs)

> ERROR in ./~/jira-connector/api/issue.js
> Module not found: Error: Cannot resolve module 'fs' in
> Portal.Client\node_modules\jira-connector\api
>  @ ./~/jira-connector/api/issue.js 4:9-22

**Comment by floralvikings** [comment]
`jira-connector` shouldn't be dependent on the `fs` [npm package](https://www.npmjs.com/package/fs), but rather the [Node.js module](https://nodejs.org/api/fs.html#fs_file_system)

Maybe you have a conflicting dependency on `fs` elsewhere?

**Comment by miguel-orange** [comment]
See line 868 of the following. https://github.com/floralvikings/jira-connector/blob/master/api/issue.js

Am I missing something, is there a different "fs"?

**Comment by miguel-orange** [comment]
okay thank you @floralvikings, let me check it out.
