### ISSUE TITLE
after new JiraClient, the jira does not have project object 

### ISSUE THREAD

**Issue by robertchen** [floralvikings/jira-connector#57]
can NOT use this as jira.issue... : 
jira.project.getProjectProperties

**Comment by floralvikings** [comment]
Please provide a minimal example demonstrating this issue; I'm unable to reproduce the problem with the information you've given.

**Comment by robertchen** [comment]
Thanks replying.  I am using ProjectClient like this way, it is able to create a project. 

var JiraClient = require('jira-connector');
var ProjectClient = require('jira-connector');
var projectClient = new ProjectClient(jira)
 projectClient.project.createProject(projectData,
        function(error, project) {
            console.log(error);
       });
