### ISSUE TITLE
Changing assignee while transistioning not possible

### ISSUE THREAD

**Issue by CapsE** [floralvikings/jira-connector#59]
There is an error in your api/issue.js line 1099. 

I'm trying to use https://docs.atlassian.com/jira/REST/server/#api/2/issue-doTransition and assign a new person to the issue while I transicion it. 
According to the doc I have to send the fields like this:
` params.fields = {
                assignee:{
                    name: person
                }
            }`
params.fields.forEach is not a function in that case though.

**Comment by guillemsola** [comment]
Not sure if I get this but as per Jira documentation during a transition only certain fields can be set 

> If a field is not configured to appear on the transition screen, then it will not be in the transition metadata, and a field validation error will occur if it is submitted.

I see it in the aforementioned example but I don't see the assignee one as able to be set in a transition in a Jira I work on. You can check them as in the documentation /rest/api/2/issue/{issueIdOrKey}/transitions?expand=transitions.fields

I can, for instance, set another value present in a transition screen using something like

```javascript
var transition = {
        'fields': {
            'customfield_10320': { name: 'Release Manager' }, 
        },
        'transition': '11',
    };

 jira.issue.transitionIssue({issueId: myIssue.id, transition}, function (statusUpdate) {...
```
