### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by marcin-bryk** [floralvikings/jira-connector#66]
Hi, would you consider supplying also .d.ts files with your project in order to enable Intelisense support during development? It would also allow to type-check files during compilation. Thanks!

Here is some additional info : http://definitelytyped.org/guides/contributing.html

Marcin

**Comment by Robotkana** [comment]
+1 Would also like to have .d.ts files.

**Comment by kylefarris** [comment]
You are welcome to add this yourselves and submit a pull request!
