### ISSUE TITLE
How to  fetch total list of issues ??

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [floralvikings/jira-connector#67]
Right I see there was privilege to fetch a particular issue by passing its key , where as how would i fetch
the list of total issues from the selected project ? referred official API documentation but no luck , is there any such privilege , please suggest me ..

**Comment by th3l0g4n** [comment]
Use search:
```
client.search.search({
   jql: 'your jql search string here'
}).then(issues => {
   // list issues for your search 
});
```
jql can be anything you would enter in JIRA itself.
See also: https://docs.atlassian.com/jira/REST/cloud/#api/2/search
