### ISSUE TITLE
small syntax error in board.js/getBoard

### ISSUE THREAD

**Issue by Sebon1980** [floralvikings/jira-connector#69]
On working with the npm module, i find out that there is a small syntax error at the uri which returns 404 on executing 
Function "getBoard" is member of the AgileBoardClient but doesn't build an AgileUrl

@ line 58:
      is written --   uri: this.jiraClient.buildURL('/board/' + opts.boardId),
      must be ---   uri: this.jiraClient.buildAgileURL('/board/' + opts.boardId),

**Comment by munawwarhussain** [comment]
agreed i am getting the same issues

**Comment by joshuaeke** [comment]
+1
