### ISSUE TITLE
Handling Certificate with Authentications

### ISSUE THREAD

**Issue by ihorizon** [floralvikings/jira-connector#75]
Hi,

Nice connector by the way - This may not really an issue in terms of your connector, but I am connecting to a dev and prod instance of Jira internally and have the following challenges with certs:

1. Dev environment: "self signed certificate in certificate chain"
2. Prod environment: "UNABLE_TO_VERIFY_LEAF_SIGNATURE"

If I have a copy of the intermediate cert is there a way to point the connector to the location of the cert in order for it to use it in the connection?

I will try a global variable, but I don't know if it will work either: process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

Thanks

Andrew

**Comment by ihorizon** [comment]
Its unfortunate way around it, but this works: process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

**Comment by mfekadu** [comment]
This helped me resolve a similar issue where I was trying to connect to a private jira server and my node.js was installed by a non-admin user. I am not sure if how my node.js was installed means anything, but thanks anyway for your solution @ihorizon
