### ISSUE TITLE
OAuth authentication not working

### ISSUE THREAD

**Issue by mien** [floralvikings/jira-connector#76]
The flow as described in the documentation is working fine till `JiraClient.oauth_util.swapRequestTokenWithAccessToken` method call. I get the access token but creating the `JiraClient`  instance with consumer_key, private_key, token and token_secret in the 4th step gives oauth_problem=token_rejected error when making a API call.

Alternatively I tried to use the access_token return by `JiraClient.oauth_util.getAuthorizeURL` method call to make the API request like http://<API_path>/?access_token=<access_token> this works fine.

Can anyone help me to clarify this issues.

**Comment by davidvexel** [comment]
I'm having the same issue:
`{ statusCode: 401, data: 'oauth_problem=token_rejected' }`

**Comment by davidvexel** [comment]
Oh nvm, I was using a wrong host on the `swapRequestTokenWithAccessToken` method.
