### ISSUE TITLE
read ECONNRESET error, how to solve? is there any option to prevent this?

### ISSUE THREAD

**Issue by mukesh-mohan** [floralvikings/jira-connector#85]
I am running some update script for a large number of issues in JIRA, so while proceeding it gives **read ECONNRESET** error for few entries. How to solve this? is there any option there to enable the keepAlive mode?

**Comment by kylefarris** [comment]
@mukesh-mohan I don't think this is a `jira-connector`-specific issue. Did you ever get this resolved?

**Comment by mukesh-mohan** [comment]
Thanks for the response @kylefarris , It was a kind of multiple request issue, which arrived when I tried to give large update request to the **API**. Later I was able to resolve the issue by using some queuing  system, where it will control the request executions by limiting in certain number at a time.

**Comment by kylefarris** [comment]
Glad you figured it out @mukesh-mohan
