### ISSUE TITLE
Updates missing on npm install.

### ISSUE THREAD

**Issue by bdesouza** [floralvikings/jira-connector#87]
I npm unstalled this library and I noticed that the version on GitHub doesn't seem to match what npm provides even though the versions are the same.

From NPM:
...
```
"author": {
    "name": "Caleb Brinkman",
    "email": "floralvikings@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/floralvikings/jira-connector/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "oauth": "^0.9.12",
    "request": "^2.51.0"
  },
  "deprecated": false,
  "description": "Easy to use NodeJS wrapper for the Jira REST API.",
  "homepage": "https://github.com/floralvikings/jira-connector#readme",
  "keywords": [
    "JIRA",
    "REST",
    "OAuth"
  ],
  "license": "MIT",
  "main": ".",
  "name": "jira-connector",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/floralvikings/jira-connector.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "2.6.0"
```

Note how the Auth api is missing below:
<img width="268" alt="screen shot 2017-11-12 at 6 09 09 pm" src="https://user-images.githubusercontent.com/664555/32706867-f2aec590-c7d4-11e7-8e90-44e4a39ecffc.png">

**Comment by bdesouza** [comment]
I should point out that the issue is resolved if I provide the github url. 
```npm install --save https://github.com/floralvikings/jira-connector.git```
as opposed to ```npm install --save jira-connector```

**Comment by floralvikings** [comment]
Yup, I'll publish a new release shortly

**Comment by floralvikings** [comment]
v2.7.0 is now published 😄 

As an aside, @kylefarris would you like to be added to the npm collaborators list?  I don't mind publishing new versions every now and again but if you'd like to be able to publish as well we can definitely do that.

**Comment by kylefarris** [comment]
Yes, that would make things much easier. Thanks.


Some people dream of success...while others wake up and work hard at it.

**Comment by kylefarris** [comment]
Yes, that would make things much easier. Thanks.

**Comment by floralvikings** [comment]
Just to make sure; you're @kylefarris on npm as well, correct?

**Comment by kylefarris** [comment]
Yep.

**Comment by floralvikings** [comment]
Added
