### ISSUE TITLE
Return JQL search result

### ISSUE THREAD

**Issue by ebiss** [floralvikings/jira-connector#89]
Hi there,

Non-coder here trying to dig into this stuff, and I'm pretty lost. I was able to write code to return values for a single issue, but I can't seem to find the right resources to write the code to return values based upon a JQL search. I tried something basic here, but I'm not sure what I'm doing wrong. Any guidance would be much appreciated, it would be huge to get this working for my company!

```javascript
var JiraClient = require('jira-connector');
 
var jira = new JiraClient( {
    host: (removed for security purposes),
    basic_auth: {
        base64: (removed for security purposes)
    }
});

jira.search.search({
   jql: 'type = bug'
}).then(issues => {
   // list issues for your search 
   function(error, issue) {
    console.log(issue.fields.issueKey, issue.fields.issuetype.name, issue.fields.summary, issue.fields.status.name, issue.fields.resolution.name, issue.fields.labels, issue.fields.customfield_12600, issue.fields.customfield_14212, issue.fields.customfield_10009, issue.fields.customfield_14200, issue.fields.customfield_14205, issue.fields.customfield_14203, issue.fields.customfield_14204, issue.fields.customfield_10004);
}
});
```

**Comment by kylefarris** [comment]
Hey @ebiss,

Welcome to the world of programming!

Seems like you just have a slight confusion between how to write callbacks (totally normal). Things are a little crazy in the JavaScript world these days. You'll see examples using classic ES5 callbacks and some examples using newer ES20xx arrow functions. You also seems to be confusing Promises with Node-style callback patterns. Here's what your code should look like:

Here's a pure ES20xx implementation (supported on any semi-recent version of NodeJS):

```javascript
const JiraClient = require('jira-connector');
 
const jira = new JiraClient( {
    host: (removed for security purposes),
    basic_auth: {
        base64: (removed for security purposes)
    }
});

jira.search.search({
    jql: 'type = bug'
}, (error, issue)  => {
    console.log(issue.fields.issueKey, issue.fields.issuetype.name, issue.fields.summary, issue.fields.status.name, issue.fields.resolution.name, issue.fields.labels, issue.fields.customfield_12600, issue.fields.customfield_14212, issue.fields.customfield_10009, issue.fields.customfield_14200, issue.fields.customfield_14205, issue.fields.customfield_14203, issue.fields.customfield_14204, issue.fields.customfield_10004);
}
});
```

Let me know if that works for you.

**Comment by ebiss** [comment]
Hi Kyle, thank you for the super-fast feedback! I think we're getting close, but when I try to run that code, I get the error "Cannot read property 'issueKey' of undefined". Any ideas?

**Comment by kylefarris** [comment]
Ah, yeah, you'll be getting back multiple issues so, if you want to just see if its working by looking at one issue, you'll need to change the last block to this:

```javascript
jira.search.search({
    jql: 'type = bug'
}, (error, issues)  => {
    if (err) throw err; // probably should be handling errors in case you get one from Jira
    const issue = issues.issues[0]; // this just gets the first issue in the resultset

    console.log(issue.fields.issueKey, issue.fields.issuetype.name, issue.fields.summary, issue.fields.status.name, issue.fields.resolution.name, issue.fields.labels, issue.fields.customfield_12600, issue.fields.customfield_14212, issue.fields.customfield_10009, issue.fields.customfield_14200, issue.fields.customfield_14205, issue.fields.customfield_14203, issue.fields.customfield_14204, issue.fields.customfield_10004);
}
});
```

Also, keep in mind that Jira is only ever going to respond with, I think, 100 results these days. You can check out my answer on issue #44 if you want to see an example of how to get ALL issues from a search.

Good luck.

**Comment by sakuta** [comment]
Hi, I'm sending simple search query:
`jira.search.search({
		jql: 'project = "MAX"'
	}, function(error, result) {
		console.log(error);
		console.log(result);
	});`
and getting the error:
`'Unrecognized field "fieldsByKeys" (Class com.atlassian.jira.rest.v2.search.SearchRequestBean), not marked as ignorable\n'`.
What am I doing wrong?

**Comment by abraham2512** [comment]
I'm facing this exact issue on a node server on ubuntu machine, but same code works fine on windows server. Please advise.

**Comment by MrRefactoring** [comment]
It's can be a bug in new version. Can you try to reproduce it in `2.16.1` version?

**Comment by sakuta** [comment]
Yes, it works with `2.16.1`. Thank you!
