### ISSUE TITLE
api/board.js/getIssuesForBacklog missing parameter support

### ISSUE THREAD

**Issue by pjuchniewicz** [floralvikings/jira-connector#92]
getIssuesForBacklog does not supporting some parameters (fields, sql, validateQuery) per
[https://developer.atlassian.com/cloud/jira/software/rest/#api-board-boardId-backlog-get](https://developer.atlassian.com/cloud/jira/software/rest/#api-board-boardId-backlog-get)

The change needed is just to pass through the parameters similar to how it is done for api/sprint.js/getSprintIssues:

qs: {
        startAt: opts.startAt,
        maxResults: opts.maxResults,
        jql: opts.jql,
        validateQuery: opts.validateQuery,
        fields: opts.fields
      }

**Comment by zfmaster** [comment]
@floralvikings, Could you, please, merge this commit? It would be very awesome, this parameters are really missing.
