### ISSUE TITLE
Download attachment

### ISSUE THREAD

**Issue by jacobweber** [floralvikings/jira-connector#97]
It doesn't look like there's a way to download an issue's attachments.

I can call `jira.issue.getIssue()` to get the attachment list, and then read the URL from `response.fields.attachment[x].content`. But I couldn't find a way to download the file from that URL (with the necessary authentication headers), or preferably, pipe it to a writable stream.

**Comment by kylefarris** [comment]
@jacobweber I'm using the request module (https://www.npmjs.com/package/request) to accomplish this.

This is a function wrote for an app that does exactly what you're trying to do (I'm using Express on the backend). I've dumbed it down a bit and made it a bit more generic for brevity's sake.

```javascript
// ****************************************************************************
// Allows a user to get attachments from JIRA proxied via this server as 
// as our API user. URLs will be provided as modified Base64-encoded strings.
// -----
// Custom string mappings to allow base64 strings in URI:
// ~ => /
// - => =
// _ => +
// -----
// ROUTE: GET /file/:url
// -----
// @param   Object      req     Express HTTP request object
// @param   Object      res     Express HTTP response object
// ****************************************************************************
function proxy_file(req, res) {
    // Get the jira download URL from the request object
    if (!req.params.url || req.params.url.length <= 0) throw new Error("Invalid URL provided!");
    const jira_url = Base64.decode(req.params.url.replace(/~/g,'/').replace(/\-/g,'=').replace(/_/g,'+'));

    // This is so we don't have to kill our proxy server everytime someone wants to load a file from Jira
    res.set('Cache-Control', 'public, max-age=31557600');

    // Make sure we have a URL before continuing...
    if (!jira_url|| typeof jira_url!== 'string' || jira_url=== 'undefined') {
        return res.download(this.env_config.server_app_path + 'public/img/generic_file.png');
    }

    // Make sure what we're fetching is an attachment, thumbnail, or avatar (we can add more if needed)
    if (!/attachment\/\d+\/.*$/.test(jira_url) && !/thumbnail\/\d+\/.*$/.test(jira_url) && !/\/secure\/viewavatar\?/.test(jira_url)) {
        throw new Error("We cannot fulfill your download request at this time.");
    }
   
    // Configure Request object to get file from Jira
    const req_options = {
        auth: {
            user: jira_config.username,
            pass: jira_config.password,
            sendImmediately: true
        }
    };
   
    // Make the request for the file...
    request.get(jira_url, req_options).on('response', response => {
        if (response.statusCode !== 200) {
            console.log("Could not get image.");
            return false;
        }
    }).on('error', (err) => {
        console.log("The error: ", err);
    }).pipe(res);
};
```

Hope that helps!

**Comment by jacobweber** [comment]
Thanks @kylefarris. I ended up doing something similar. Would be nice to have it as part of jira-connector though.

**Comment by kylefarris** [comment]
Its probably just a bit too outside the scope and fairly simple to implement.

**Comment by nslcorp** [comment]
I also got this issue
but solution @kylefarris doesn't work for me

I found that there is necessary header


> Scripts that access Jira remotely may have trouble acquiring or returning a security token, or maintaining an HTTP session with the server. There is a way for scripts to opt out of token checking by providing the following HTTP header in the request:
X-Atlassian-Token: no-check

https://developer.atlassian.com/server/jira/platform/form-token-handling/

**Comment by ric2b** [comment]
Could this be reconsidered?

The library has functionality to upload attachments so this doesn't look out of scope to me.

It's nice to be able to pass around a `jira` client object which I can use to make calls to the API but then when I need to download an attachment the complexity increases significantly because the library doesn't support it:

- I need to import an http library and understand how Jira authentication works, and handle it myself with said http library.
- I need to get the credentials from somewhere.
