### ISSUE TITLE
Basic auth with password to be deprecated on Jira cloud APIs - start using API tokens

### ISSUE THREAD

**Issue by mansilladev** [floralvikings/jira-connector#98]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for passwords in HTTP basic auth requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by endymion** [comment]
I can confirm that jira-connector works with API tokens with no modification.

You get a token from the JIRA dashboard.  Then you simply use the token with basic authentication in place of your password.  No change is necessary to the basic authentication feature in jira-connector.  Maybe a documentation tweak, to explain how to do it.

**Comment by gareth-johnstone** [comment]
has anyone got a code sample as to how to use authentication with the API tokens? i cant seem to get it to work!
