### ISSUE TITLE
Add Attachment

### ISSUE THREAD

**Issue by zeshanvirk** [floralvikings/jira-connector#99]
I'm unable to add attachment to existing issue using jira-connector **jira.issue.addAttachment()** method , where to provide the **issue key** and **file** ? can any provide me the sample code?

**Comment by Emirati** [comment]
Here is an example of what you code should look like: 

`jira.issue.addAttachment({
      issueKey: "PRO-1111",
      filename: '/path/to/your/file'
 }, function(error, response) {
      console.log(response);
})`
